name: Documentation
description: Report missing, unclear, or incorrect documentation
title: "docs: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve the documentation!

  - type: textarea
    id: what
    attributes:
      label: What needs documenting?
      description: What topic, feature, or process needs better documentation?
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current State
      description: What does the current documentation say (if anything)?
      placeholder: The README mentions X but doesn't explain how to...
    validations:
      required: false

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: What would you like to see documented?
    validations:
      required: true
