from .core import init_db, is_db_initialized, db_exists, DB_PATH, reset_db_connection
from .crud import (
    create_memory,
    get_memories,
    get_memory,
    get_memory_by_url,
    delete_memory,
    update_memory,
    update_memory_embedding,
    update_memory_summary,
    get_memories_without_embeddings,
    count_memories_with_embeddings,
    count_memories_needing_reembedding,
    get_memories_needing_reembedding,
    get_setting,
    set_setting,
    delete_setting,
    # Tag functions
    get_all_tags,
    get_or_create_tag,
    add_tags_to_memory,
    remove_tag_from_memory,
    get_memory_tags,
)
from .search import search_similar_memories

__all__ = [
    "init_db",
    "is_db_initialized",
    "db_exists",
    "DB_PATH",
    "reset_db_connection",
    "create_memory",
    "get_memories",
    "get_memory",
    "get_memory_by_url",
    "delete_memory",
    "update_memory",
    "update_memory_embedding",
    "update_memory_summary",
    "get_memories_without_embeddings",
    "count_memories_with_embeddings",
    "count_memories_needing_reembedding",
    "get_memories_needing_reembedding",
    "get_setting",
    "set_setting",
    "delete_setting",
    "search_similar_memories",
    # Tag functions
    "get_all_tags",
    "get_or_create_tag",
    "add_tags_to_memory",
    "remove_tag_from_memory",
    "get_memory_tags",
]
